-- TODO: Use up and down arrows in insert mode or j and k in normal mode to navigate through the history
-- TODO: Figure out a better way to do syntax highlighting. Current method just sets the buffer ft to vim
-- TODO: Prevent windows from closing other hover windows. E.g. don't close a focused hover doc window and return to it after command/search
-- TODO: Fix the history view stuff.
